### ISSUE TITLE
Bussiness logic checklist

### ISSUE THREAD

**Issue by triandamai** [TimKelompok5/mobile-app#42]
Modul data akan di mulai setelah UI selesai
Persiapan sebelum masuk ke data

Di aplikasi data apa saja yang perlu disimpan di database?:

- [ ] user #43
- [ ] podcast #46
- [ ] history search #54
- [x] episodes #68 
- [ ] topic #46
- [ ] level user #117 

Fungsi apa saja yang perlu dibuat?

- [x] cek sudah login 
- [x] logout #92 
- [x] login email&password #72 
- [x] login google #75 
- [x] register email&password #73 
- [x] register google #86 
- [x] save topic #88 #76 
- [x] save complete profile #87 
- [x] save photo profile #99
- [x] search podcast #100
- [x] get list podcast #93
- [x] get list top episode #98
- [x] get history search #97
- [x] get detail podcast #96
- [x] get detail episode #95
- [x] get list topic #89 
- [x] get trending podcast #94
- [x] #107 
- [x] #109 
- [ ] #127

**Comment by triandamai** [comment]
```text
USER--------+
            +- uid(random)
                +- name
                +- email
                +- address
                +- photoProfile
                +- dateOfBirth
                +- gender
                    +- TOPICS
                        +- id_topic
                            +- name
                            +- image
                            +- key
                            +- color
                    +- HISTORY_SEARCH
                        +-uid(random)
                            +- episode
                            +- createdAt
                            +- 
                    +- LISTENING
                        +- uid
                            +- episode
                            
PODCAST-----+ 
            +- uid(random)
                +- title
                +- description
                +- createdAt
                +- createdBy
                    +- EPISODE
                        +- id_episode
                            +- title
                            +- description
                            +- createdBy
                            +- durationHours
                            +- durationMinutes

EPISODES----+ 
            +- uid(random)
                +- title
                +- description
                +- createdBy
                +- durationHours
                +- durationMinutes
                +- podcastId

TOPICS------+
            +- uid(randoom)
                +- name
                +- image
                +- key
                +- color
```

**Comment by triandamai** [comment]
Referensi


Untuk Autentikasi(Login,Register)
https://firebase.google.com/docs/auth/flutter/password-auth?hl=en&authuser=0
https://firebase.google.com/docs/auth/flutter/federated-auth?hl=en&authuser=0

Untuk database(data user,podcast,topic, dll)
https://firebase.google.com/docs/firestore/manage-data/add-data?hl=en&authuser=0
https://firebase.google.com/docs/firestore/query-data/get-data?hl=en&authuser=0

Untuk file(simpan audio,gambar dll)
https://firebase.google.com/docs/storage/flutter/upload-files?hl=en&authuser=0
https://firebase.google.com/docs/storage/flutter/download-files?hl=en&authuser=0
https://firebase.google.com/docs/storage/flutter/delete-files?hl=en&authuser=0

**Comment by marioprasetyo** [comment]
Schema data playlist: 
- data love user
-  data episode podcast

**Comment by marioprasetyo** [comment]
fungsi ketika user follow creator akan mendapatkan update notifikasi podcast yang baru di upload (mirip fitur subscriber youtube dengan notifikasi)

**Comment by marioprasetyo** [comment]
fungsi trending minggu ini berdasarkan jumlah share podcast

**Comment by marioprasetyo** [comment]
fungsi top episode berdasarkan jumlah love semua user.

**Comment by marioprasetyo** [comment]
fungsi panduan gapai cita cita berdasarkan random data audiobook

**Comment by marioprasetyo** [comment]
fungsi download offline?

**Comment by triandamai** [comment]
```dart
Navigator.of(context).pushNamed(Routes.detailDetailEpisode,
    arguments: {
         'id':""
    });
```
ambil argument:

```dart
final routes=ModalRoute.of(context)?.settings.arguments as Map<String,String>;

    if(routes['id'] == null){

      context.read<EpisodeProvider>().getDetailEpisode(routes['id']!);
    }
```
